spring:
  datasource:
    url: jdbc:postgresql://ep-empty-union-a53wc52n.us-east-2.aws.neon.tech/fileupload?sslmode=require
    username: springprojetDB_owner
    password: JLo7T9vlmVgq
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 3000000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Add this line

  data:
    redis:
      password: rMrKyYmNUwy2bvuJbDguWtpwY1heT819
      host: redis-10449.c265.us-east-1-2.ec2.redns.redis-cloud.com
      port: 10449
      timeout: 10000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1